# Generated by Django 4.1.7 on 2023-04-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('o_price', models.FloatField()),
                ('o_date', models.DateTimeField()),
                ('product', models.CharField(max_length=60)),
                ('add', models.CharField(max_length=60)),
            ],
        ),
    ]
